services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq_management
    ports:
      - "5672:5672"
      - "25672:25672" # (erlang) communication between the nodes and CLI tool
      - "15672:15672" # communication with the web management API
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123123
